//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.Account.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covi.Features.Account.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is already taken..
        /// </summary>
        internal static string CreateProfileValidationException_DuplicateUserName_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_DuplicateUserName_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        internal static string CreateProfileValidationException_Password_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_Password_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        internal static string CreateProfileValidationException_PasswordRequiresDigit_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_PasswordRequiresDigit_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one non-alphanumeric character..
        /// </summary>
        internal static string CreateProfileValidationException_PasswordRequiresNonAlphanumeric_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_PasswordRequiresNonAlphanumeric_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;) letter..
        /// </summary>
        internal static string CreateProfileValidationException_PasswordRequiresUpper_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_PasswordRequiresUpper_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        internal static string CreateProfileValidationException_PasswordTooShort_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_PasswordTooShort_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username field is required..
        /// </summary>
        internal static string CreateProfileValidationException_Username_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_Username_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password not recognised..
        /// </summary>
        internal static string LoginException_InvalidGrant_ErrorText {
            get {
                return ResourceManager.GetString("LoginException_InvalidGrant_ErrorText", resourceCulture);
            }
        }
    }
}
