//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.UserLogOut.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Covi.Features.UserLogOut.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Menu_LogOut_Dialog_AcceptBtn {
            get {
                return ResourceManager.GetString("Menu_LogOut_Dialog_AcceptBtn", resourceCulture);
            }
        }
        
        internal static string Menu_LogOut_Dialog_CancelBtn {
            get {
                return ResourceManager.GetString("Menu_LogOut_Dialog_CancelBtn", resourceCulture);
            }
        }
        
        internal static string Menu_LogOut_Dialog_QuestionText {
            get {
                return ResourceManager.GetString("Menu_LogOut_Dialog_QuestionText", resourceCulture);
            }
        }
        
        internal static string Menu_Exit_Dialog_QuestionText {
            get {
                return ResourceManager.GetString("Menu_Exit_Dialog_QuestionText", resourceCulture);
            }
        }
        
        internal static string Menu_LogOut_Dialog_TitleText {
            get {
                return ResourceManager.GetString("Menu_LogOut_Dialog_TitleText", resourceCulture);
            }
        }
        
        internal static string Menu_Exit_Dialog_TitleText {
            get {
                return ResourceManager.GetString("Menu_Exit_Dialog_TitleText", resourceCulture);
            }
        }
        
        internal static string Menu_LogOut_ItemText {
            get {
                return ResourceManager.GetString("Menu_LogOut_ItemText", resourceCulture);
            }
        }
        
        internal static string Menu_Exit_ItemText {
            get {
                return ResourceManager.GetString("Menu_Exit_ItemText", resourceCulture);
            }
        }
    }
}
