//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.UserProfile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covi.Features.UserProfile.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open this app regularly when around others to enhance your bluetooth connectivity..
        /// </summary>
        internal static string Bluetooth_Reminder_Description_Text {
            get {
                return ResourceManager.GetString("Bluetooth_Reminder_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLUETOOTH CONNECTIVITY.
        /// </summary>
        internal static string Bluetooth_Reminder_Title_Text {
            get {
                return ResourceManager.GetString("Bluetooth_Reminder_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE STATUS.
        /// </summary>
        internal static string ChangeStatusLink_Button_Text {
            get {
                return ResourceManager.GetString("ChangeStatusLink_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the link below to update your health status.
        /// </summary>
        internal static string ChangeStatusLink_Explanation_Text {
            get {
                return ResourceManager.GetString("ChangeStatusLink_Explanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All information in this app is encrypted and  totally anonymous..
        /// </summary>
        internal static string Encryption_Status_Description_Text {
            get {
                return ResourceManager.GetString("Encryption_Status_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENCRYPTION.
        /// </summary>
        internal static string Encryption_Status_Title_Text {
            get {
                return ResourceManager.GetString("Encryption_Status_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Health Status is: {0}.  To stay safe, please follow the government guidlines and recommendations..
        /// </summary>
        internal static string HealthStatus_Advice_Description_Default_TextFormat {
            get {
                return ResourceManager.GetString("HealthStatus_Advice_Description_Default_TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out more.
        /// </summary>
        internal static string HealthStatus_Advice_MoreInfo_Text {
            get {
                return ResourceManager.GetString("HealthStatus_Advice_MoreInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEALTH STATUS ADVICE.
        /// </summary>
        internal static string HealthStatus_Advice_Title_Text {
            get {
                return ResourceManager.GetString("HealthStatus_Advice_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROTECTING.
        /// </summary>
        internal static string Profile_Protecting_Text {
            get {
                return ResourceManager.GetString("Profile_Protecting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string UserProfile_Title_Text {
            get {
                return ResourceManager.GetString("UserProfile_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1} days.
        /// </summary>
        internal static string UserStatus_StatusCountdown_TextFormat {
            get {
                return ResourceManager.GetString("UserStatus_StatusCountdown_TextFormat", resourceCulture);
            }
        }
    }
}
