//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.CreateProfile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covi.Features.CreateProfile.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string CreateProfile_Confirm_Password_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Confirm_Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string CreateProfile_ConfirmPassword_Label_Text {
            get {
                return ResourceManager.GetString("CreateProfile_ConfirmPassword_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        internal static string CreateProfile_Expander_Header_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Expander_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you’re an official health care worker, please switch on this option. This will enable you to generate your codes to send to your patients so as they can change their status..
        /// </summary>
        internal static string CreateProfile_Expander_Main_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Expander_Main_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Id should not be empty.
        /// </summary>
        internal static string CreateProfile_Medical_EmptyErrorMessage_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Medical_EmptyErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health ID.
        /// </summary>
        internal static string CreateProfile_Medical_Entry_Placeholder_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Medical_Entry_Placeholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health ID.
        /// </summary>
        internal static string CreateProfile_Medical_Title_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Medical_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step.
        /// </summary>
        internal static string CreateProfile_Next_Button_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Next_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am an official health care worker.
        /// </summary>
        internal static string CreateProfile_OfficialHealthCare_Label_Text {
            get {
                return ResourceManager.GetString("CreateProfile_OfficialHealthCare_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create profile.
        /// </summary>
        internal static string CreateProfile_PageName_Text {
            get {
                return ResourceManager.GetString("CreateProfile_PageName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string CreateProfile_Password_Label_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Password_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string CreateProfile_Password_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least:.
        /// </summary>
        internal static string CreateProfile_PasswordRequirements_Text {
            get {
                return ResourceManager.GetString("CreateProfile_PasswordRequirements_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 characters.
        /// </summary>
        internal static string CreateProfile_Requirement_1_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 upper case letter.
        /// </summary>
        internal static string CreateProfile_Requirement_2_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 lower case letter.
        /// </summary>
        internal static string CreateProfile_Requirement_3_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 special symbol and a digit.
        /// </summary>
        internal static string CreateProfile_Requirement_4_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should not be empty..
        /// </summary>
        internal static string CreateProfile_Requirement_Filled_Username_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_Filled_Username_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmation password should be the same..
        /// </summary>
        internal static string CreateProfile_Requirement_Same_Passwords_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_Same_Passwords_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your anonymous profile.
        /// </summary>
        internal static string CreateProfile_Title_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string CreateProfile_Username_Entry_Placeholder_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Username_Entry_Placeholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a username.
        /// </summary>
        internal static string CreateProfile_Username_Label_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Username_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters in username are not allowed.
        /// </summary>
        internal static string CreateProfileValidationException_Username_HasSpecialSymbolErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_Username_HasSpecialSymbolErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string SignUp_AlreadyHaveAnAccount_Text {
            get {
                return ResourceManager.GetString("SignUp_AlreadyHaveAnAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string SignUp_LoginBtn_Text {
            get {
                return ResourceManager.GetString("SignUp_LoginBtn_Text", resourceCulture);
            }
        }
    }
}
