//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Covi.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Dialog_Accept {
            get {
                return ResourceManager.GetString("Dialog_Accept", resourceCulture);
            }
        }
        
        public static string ErrorDialog_Message_Generic {
            get {
                return ResourceManager.GetString("ErrorDialog_Message_Generic", resourceCulture);
            }
        }
        
        public static string ErrorDialog_Title {
            get {
                return ResourceManager.GetString("ErrorDialog_Title", resourceCulture);
            }
        }
        
        public static string Exception_NoInternetConnection {
            get {
                return ResourceManager.GetString("Exception_NoInternetConnection", resourceCulture);
            }
        }
        
        public static string Exception_TimedOut_Text {
            get {
                return ResourceManager.GetString("Exception_TimedOut_Text", resourceCulture);
            }
        }
        
        public static string Exception_UnderMaintenance {
            get {
                return ResourceManager.GetString("Exception_UnderMaintenance", resourceCulture);
            }
        }
        
        public static string Exception_Unknown {
            get {
                return ResourceManager.GetString("Exception_Unknown", resourceCulture);
            }
        }
        
        public static string Exception_UpdateRequired {
            get {
                return ResourceManager.GetString("Exception_UpdateRequired", resourceCulture);
            }
        }
        
        public static string Global_EPAM_Text {
            get {
                return ResourceManager.GetString("Global_EPAM_Text", resourceCulture);
            }
        }
        
        public static string Global_PoweredBy_Text {
            get {
                return ResourceManager.GetString("Global_PoweredBy_Text", resourceCulture);
            }
        }
        
        public static string Component_Info_SomethingWrong_Text {
            get {
                return ResourceManager.GetString("Component_Info_SomethingWrong_Text", resourceCulture);
            }
        }
        
        public static string Component_Info_Retry_Text {
            get {
                return ResourceManager.GetString("Component_Info_Retry_Text", resourceCulture);
            }
        }
    }
}
