// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Article
    {
        /// <summary>
        /// Initializes a new instance of the Article class.
        /// </summary>
        public Article()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Article class.
        /// </summary>
        public Article(string id = default(string), string languageCode = default(string), string source = default(string), string title = default(string), System.DateTime? created = default(System.DateTime?), ArticleBody body = default(ArticleBody), VideoLink videoLink = default(VideoLink), ImageLink imageLink = default(ImageLink))
        {
            Id = id;
            LanguageCode = languageCode;
            Source = source;
            Title = title;
            Created = created;
            Body = body;
            VideoLink = videoLink;
            ImageLink = imageLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "languageCode")]
        public string LanguageCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "body")]
        public ArticleBody Body { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "videoLink")]
        public VideoLink VideoLink { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "imageLink")]
        public ImageLink ImageLink { get; set; }

    }
}
