// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FilterValue
    {
        /// <summary>
        /// Initializes a new instance of the FilterValue class.
        /// </summary>
        public FilterValue()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FilterValue class.
        /// </summary>
        public FilterValue(string displayName = default(string), string parameterName = default(string), bool? isDefault = default(bool?))
        {
            DisplayName = displayName;
            ParameterName = parameterName;
            IsDefault = isDefault;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parameterName")]
        public string ParameterName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDefault")]
        public bool? IsDefault { get; set; }

    }
}
