// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Filter
    {
        /// <summary>
        /// Initializes a new instance of the Filter class.
        /// </summary>
        public Filter()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Filter class.
        /// </summary>
        public Filter(string displayName = default(string), string parameterName = default(string), bool? isMultiSelect = default(bool?), IList<FilterValue> values = default(IList<FilterValue>))
        {
            DisplayName = displayName;
            ParameterName = parameterName;
            IsMultiSelect = isMultiSelect;
            Values = values;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parameterName")]
        public string ParameterName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isMultiSelect")]
        public bool? IsMultiSelect { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "values")]
        public IList<FilterValue> Values { get; set; }

    }
}
