// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ImageLink
    {
        /// <summary>
        /// Initializes a new instance of the ImageLink class.
        /// </summary>
        public ImageLink()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ImageLink class.
        /// </summary>
        public ImageLink(string imageId = default(string), string url = default(string))
        {
            ImageId = imageId;
            Url = url;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "imageId")]
        public string ImageId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

    }
}
