// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NotificationInfo
    {
        /// <summary>
        /// Initializes a new instance of the NotificationInfo class.
        /// </summary>
        public NotificationInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NotificationInfo class.
        /// </summary>
        public NotificationInfo(string token, string targetPlatform)
        {
            Token = token;
            TargetPlatform = targetPlatform;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public string Token { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "targetPlatform")]
        public string TargetPlatform { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Token == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Token");
            }
            if (TargetPlatform == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TargetPlatform");
            }
        }
    }
}
