// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class VideoLink
    {
        /// <summary>
        /// Initializes a new instance of the VideoLink class.
        /// </summary>
        public VideoLink()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VideoLink class.
        /// </summary>
        public VideoLink(string title = default(string), string uri = default(string))
        {
            Title = title;
            Uri = uri;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

    }
}
