//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.ApplyCode.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covi.Features.ApplyCode.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY CODE.
        /// </summary>
        internal static string ApplyCode_Btn_Text {
            get {
                return ResourceManager.GetString("ApplyCode_Btn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is not recognized.
        /// </summary>
        internal static string ApplyCode_InputError_Text {
            get {
                return ResourceManager.GetString("ApplyCode_InputError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your code here.
        /// </summary>
        internal static string ApplyCode_InputPlaceholder_Text {
            get {
                return ResourceManager.GetString("ApplyCode_InputPlaceholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By continuing you are allowing us to inform others that they may be at risk of infection. This could save their life..
        /// </summary>
        internal static string ApplyCode_PageDescription1_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageDescription1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember, this app never tracks your location or identity. You are completely anonymous..
        /// </summary>
        internal static string ApplyCode_PageDescription2_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageDescription2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for helping keep others safe..
        /// </summary>
        internal static string ApplyCode_PageDescription3_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageDescription3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your code.
        /// </summary>
        internal static string ApplyCode_PageName_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the unique code your healthcare professional has given you. This will update your health status in this app..
        /// </summary>
        internal static string ApplyCode_PageTitle1_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageTitle1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your status and save lives.
        /// </summary>
        internal static string ApplyCode_PageTitle2_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageTitle2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical code is expired..
        /// </summary>
        internal static string ApplyCodeExpiredException_ErrorText {
            get {
                return ResourceManager.GetString("ApplyCodeExpiredException_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical code not found or already taken..
        /// </summary>
        internal static string ApplyCodeNotFoundException_ErrorText {
            get {
                return ResourceManager.GetString("ApplyCodeNotFoundException_ErrorText", resourceCulture);
            }
        }
    }
}
