//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.MedicalLogin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covi.Features.MedicalLogin.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health security id is already taken or expired..
        /// </summary>
        internal static string MedicalAuthenticationException_InvalidHealthSecurityId_ErrorText {
            get {
                return ResourceManager.GetString("MedicalAuthenticationException_InvalidHealthSecurityId_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE.
        /// </summary>
        internal static string MedicalLogIn_Btn_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_Btn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health security ID.
        /// </summary>
        internal static string MedicalLogIn_Entry_Placeholder_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_Entry_Placeholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health ID not recognized.
        /// </summary>
        internal static string MedicalLogIn_Entry_Requirements_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_Entry_Requirements_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Id should not be empty.
        /// </summary>
        internal static string MedicalLogIn_MedicalId_EmptyErrorMessage_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_MedicalId_EmptyErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        internal static string MedicalLogIn_PageName_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_PageName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section of the app is for healthcare professionals only. Please enter your health security ID to continue..
        /// </summary>
        internal static string MedicalLogIn_Title_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_Title_Text", resourceCulture);
            }
        }
    }
}
