//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.Rumours.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Covi.Features.Rumours.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Menu_Rumours_ItemText {
            get {
                return ResourceManager.GetString("Menu_Rumours_ItemText", resourceCulture);
            }
        }
        
        internal static string Rumours_CreateAccount_BtnText {
            get {
                return ResourceManager.GetString("Rumours_CreateAccount_BtnText", resourceCulture);
            }
        }
        
        internal static string Rumours_Header_TitleText {
            get {
                return ResourceManager.GetString("Rumours_Header_TitleText", resourceCulture);
            }
        }
        
        internal static string Rumours_InfoItem1_Text {
            get {
                return ResourceManager.GetString("Rumours_InfoItem1_Text", resourceCulture);
            }
        }
        
        internal static string Rumours_InfoItem2_Text {
            get {
                return ResourceManager.GetString("Rumours_InfoItem2_Text", resourceCulture);
            }
        }
        
        internal static string Rumours_Input_Placeholder_Text {
            get {
                return ResourceManager.GetString("Rumours_Input_Placeholder_Text", resourceCulture);
            }
        }
        
        internal static string Rumours_LogIn_BtnText {
            get {
                return ResourceManager.GetString("Rumours_LogIn_BtnText", resourceCulture);
            }
        }
        
        internal static string Rumours_Restricted_TitleText {
            get {
                return ResourceManager.GetString("Rumours_Restricted_TitleText", resourceCulture);
            }
        }
        
        internal static string Rumours_TabTitle_Text {
            get {
                return ResourceManager.GetString("Rumours_TabTitle_Text", resourceCulture);
            }
        }
    }
}
