//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.OnBoarding.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Covi.Features.OnBoarding.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BluetoothNotification_Denied_ErrorText {
            get {
                return ResourceManager.GetString("BluetoothNotification_Denied_ErrorText", resourceCulture);
            }
        }
        
        internal static string BluetoothNotification_Disabled_ErrorText {
            get {
                return ResourceManager.GetString("BluetoothNotification_Disabled_ErrorText", resourceCulture);
            }
        }
        
        internal static string BluetoothNotification_Error_Title {
            get {
                return ResourceManager.GetString("BluetoothNotification_Error_Title", resourceCulture);
            }
        }
        
        internal static string BluetoothNotification_NotSupported_WarningText {
            get {
                return ResourceManager.GetString("BluetoothNotification_NotSupported_WarningText", resourceCulture);
            }
        }
        
        internal static string BluetoothNotification_Warning_Title {
            get {
                return ResourceManager.GetString("BluetoothNotification_Warning_Title", resourceCulture);
            }
        }
        
        internal static string OnBoardind_MadeForYou_SubTitle {
            get {
                return ResourceManager.GetString("OnBoardind_MadeForYou_SubTitle", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Connectivity_ErrorText {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_ErrorText", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Connectivity_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Instruction1", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Connectivity_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Instruction2", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Connectivity_Instruction4_AndroidOnly {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Instruction4_AndroidOnly", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Connectivity_SubTitle {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_SubTitle", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Connectivity_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Title", resourceCulture);
            }
        }
        
        internal static string OnBoarding_MadeForYou_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Instruction1", resourceCulture);
            }
        }
        
        internal static string OnBoarding_MadeForYou_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Instruction2", resourceCulture);
            }
        }
        
        internal static string OnBoarding_MadeForYou_Instruction3 {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Instruction3", resourceCulture);
            }
        }
        
        internal static string OnBoarding_MadeForYou_Title {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Title", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Next_Button_Text {
            get {
                return ResourceManager.GetString("OnBoarding_Next_Button_Text", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Notifications_ErrorText {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_ErrorText", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Notifications_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Instruction1", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Notifications_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Instruction2", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Notifications_Instruction3 {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Instruction3", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Notifications_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Title", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Privacy_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Instruction1", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Privacy_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Instruction2", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Privacy_Instruction3 {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Instruction3", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Privacy_SubTitle {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_SubTitle", resourceCulture);
            }
        }
        
        internal static string OnBoarding_Privacy_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Title", resourceCulture);
            }
        }
    }
}
