//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.MedicalChangeStatus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covi.Features.MedicalChangeStatus.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StatusChangedOn field is required..
        /// </summary>
        internal static string ChangeStatusCodeGenerationException_StatusChangedOn_ErrorText {
            get {
                return ResourceManager.GetString("ChangeStatusCodeGenerationException_StatusChangedOn_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StatusId field is required..
        /// </summary>
        internal static string ChangeStatusCodeGenerationException_StatusId_ErrorText {
            get {
                return ResourceManager.GetString("ChangeStatusCodeGenerationException_StatusId_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CODE.
        /// </summary>
        internal static string Medical_CreateCodeBtn_Text {
            get {
                return ResourceManager.GetString("Medical_CreateCodeBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Medical_EditBtn_Text {
            get {
                return ResourceManager.GetString("Medical_EditBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the status for the code.
        /// </summary>
        internal static string Medical_FirstStep_Description {
            get {
                return ResourceManager.GetString("Medical_FirstStep_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 01.
        /// </summary>
        internal static string Medical_FirstStep_Title {
            get {
                return ResourceManager.GetString("Medical_FirstStep_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the patients status.
        /// </summary>
        internal static string Medical_FirstStepEmpty_Error {
            get {
                return ResourceManager.GetString("Medical_FirstStepEmpty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select when the patient approximately first became infected.
        /// </summary>
        internal static string Medical_SecondStep_Description {
            get {
                return ResourceManager.GetString("Medical_SecondStep_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 02.
        /// </summary>
        internal static string Medical_SecondStep_Title {
            get {
                return ResourceManager.GetString("Medical_SecondStep_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate patient code.
        /// </summary>
        internal static string Medical_ThirdStep_Description {
            get {
                return ResourceManager.GetString("Medical_ThirdStep_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 03.
        /// </summary>
        internal static string Medical_ThirdStep_Title {
            get {
                return ResourceManager.GetString("Medical_ThirdStep_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical.
        /// </summary>
        internal static string Medical_Title_Text {
            get {
                return ResourceManager.GetString("Medical_Title_Text", resourceCulture);
            }
        }
    }
}
